AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend infrastructure for the Cloud Resume Challenge

Parameters:
  DynamoDBTableName:
    Type: String
    Description: Name of the DynamoDB table to store visitor counts
    Default: count
  IAMRoleArn:
    Type: String
    Description: ARN of the IAM role for Lambda function

Resources:
  VisitorCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  VisitorCounterApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
      AllowMethods:
        - GET
        - POST
        - OPTIONS
      AllowOrigins:
        - "*"
      StageName: default

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: counter_function
      CodeUri: deployment.zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role: !Ref IAMRoleArn
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
      Events:
        VisitGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref VisitorCounterApi
            Path: /visit
            Method: GET
        VisitPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref VisitorCounterApi
            Path: /visit
            Method: POST

Outputs:
  ApiEndpoint:
    Description: "API Endpoint URL"
    Value: !Sub "https://${VisitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com"
