AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:  Backend infrastructure for the Cloud Resume Challenge

Parameters:
  DynamoDBTableName:
    Type: String
    Description: Name of the DynamoDB table to store visitor counts
    Default: count  # Use the name from your CloudFormation template

Resources:
  VisitorCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName #changed to use the parameter
      AttributeDefinitions:
        - AttributeName: key
          AttributeType: S
      KeySchema:
        - AttributeName: key
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: counter_function # Use the name from your CloudFormation template
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Role: !GetAtt IAMRoleAdminlambdarole.Arn # Use the existing role
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName # Pass the table name

  VisitorCounterApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: visitor-counter-api #keep name
      DefinitionBody:
        openapi: "3.0.0"
        info:
          title: Visitor Counter API
        paths:
          /visit:
            post:
              summary: Increment visitor count
              x-amazon-apigateway-integration:
                payloadFormatVersion: "1.0"
                type: AWS_PROXY
                httpMethod: POST
                uri:
                  $ref: >-
                    'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${VisitorCounterFunction.Arn}/invocations'
            get:
              summary: Get visitor count
              x-amazon-apigateway-integration:
                payloadFormatVersion: "1.0"
                type: AWS_PROXY
                httpMethod: GET
                uri:
                  $ref: >-
                    'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${VisitorCounterFunction.Arn}/invocations'
      # CORS configuration
      Cors:
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowOrigin: "*" #  Replace with your actual domain(s)

Outputs:
  ApiEndpoint:
    Description: "API Endpoint URL"
    Value: !Sub "https://${VisitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com"
