name: Deploy Backend

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_BACKEND }}
  STACK_NAME: cloud-resume-backend
  S3_BUCKET: ${{ secrets.S3_BUCKET_BACKEND }}  # <<< NEW: Create and store your S3 bucket name in GitHub secrets

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
          mkdir -p build
          cp src/lambda_function.py build/
          pip install -r src/requirements.txt -t build/

      - name: Package Lambda function
        run: |
          cd build
          zip -r ../deployment.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          role-session-name: GitHubActionsBackendDeploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Package CloudFormation template and upload to S3
        run: |
          aws cloudformation package \
            --template-file template.yaml \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --output-template-file packaged.yaml

      - name: Deploy packaged template to CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file packaged.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.AWS_REGION }} \
            --no-fail-on-empty-changeset

      - name: Run Tests
        run: python -m unittest discover src/tests
