name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Package Lambda function
        run: |
          mkdir -p build
          cp src/lambda_function.py build/lambda_function.py
          cp src/requirements.txt build/requirements.txt
          pip install -r build/requirements.txt -t build
          cd build
          zip -r ../deployment.zip .

      - name: Deploy with SAM
        uses: aws-actions/deploy-cloudformation@v1
        with:
          template: template.yaml
          stack-name: your-stack-name # Replace with your stack name
          capabilities: CAPABILITY_IAM
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Use GitHub secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Use GitHub secrets
          aws-region: your-aws-region # Replace with your AWS region

      - name: Run Tests
        run: python -m unittest discover src/tests
